<?php
declare(strict_types=1);session_start();header('Content-Type: application/json');
$db=new PDO('sqlite:'.__DIR__.'/velora.sqlite');$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY, email TEXT UNIQUE, password TEXT, username TEXT UNIQUE, verified INTEGER DEFAULT 0, verify_code TEXT, created_at TEXT); CREATE TABLE IF NOT EXISTS profiles(user_id INTEGER PRIMARY KEY, display_name TEXT, bio TEXT, avatar TEXT, banner TEXT, theme TEXT DEFAULT "violet", blocks TEXT DEFAULT "[]", views INTEGER DEFAULT 0);');
$in=json_decode(file_get_contents('php://input'),true)?:$_POST;$action=$in['action']??'';function out($x,$code=200){http_response_code($code);echo json_encode($x);exit;}function me(){if(empty($_SESSION['uid']))out(['error'=>'Nejsi přihlášen.'],401);return(int)$_SESSION['uid'];}
if($action==='register'){$email=filter_var($in['email']??'',FILTER_VALIDATE_EMAIL);$pass=$in['password']??'';if(!$email||strlen($pass)<8)out(['error'=>'Zadej platný e-mail a alespoň 8 znaků.'],422);$code=bin2hex(random_bytes(16));try{$s=$db->prepare('INSERT INTO users(email,password,verify_code,created_at)VALUES(?,?,?,datetime("now"))');$s->execute([$email,password_hash($pass,PASSWORD_DEFAULT),$code]);$id=(int)$db->lastInsertId();$db->prepare('INSERT INTO profiles(user_id,display_name,bio)VALUES(?,?,?)')->execute([$id,'Nový profil','Přidej něco o sobě.']);$_SESSION['pending']=$id;/* Integrace e-mailu: mail($email,"Ověření Velora","Ověř svůj účet: https://domena.cz/api.php?action=verify&code=$code"); */out(['ok'=>true,'next'=>'verify','devCode'=>$code]);}catch(PDOException $e){out(['error'=>'Tento e-mail už používá jiný účet.'],409);}}
if($action==='verify'){$uid=(int)($_SESSION['pending']??0);if(!$uid)out(['error'=>'Ověření vypršelo.'],400);$s=$db->prepare('SELECT verify_code FROM users WHERE id=?');$s->execute([$uid]);if(!hash_equals((string)$s->fetchColumn(),(string)($in['code']??'')))out(['error'=>'Neplatný ověřovací kód.'],403);$db->prepare('UPDATE users SET verified=1,verify_code=NULL WHERE id=?')->execute([$uid]);$_SESSION['uid']=$uid;unset($_SESSION['pending']);out(['ok'=>true,'next'=>'claim']);}
if($action==='login'){$s=$db->prepare('SELECT * FROM users WHERE email=?');$s->execute([$in['email']??'']);$u=$s->fetch(PDO::FETCH_ASSOC);if(!$u||!password_verify($in['password']??'',$u['password']))out(['error'=>'Nesprávný e-mail nebo heslo.'],401);if(!$u['verified'])out(['error'=>'Nejdřív ověř svůj e-mail.'],403);$_SESSION['uid']=$u['id'];out(['ok'=>true,'next'=>$u['username']?'dashboard':'claim']);}
if($action==='claim'){$uid=me();$name=strtolower(trim($in['username']??''));if(!preg_match('/^[a-z0-9_-]{3,24}$/',$name))out(['error'=>'Použij 3–24 znaků: písmena, čísla, _ nebo -.'],422);try{$db->prepare('UPDATE users SET username=? WHERE id=?')->execute([$name,$uid]);$db->prepare('UPDATE profiles SET display_name=? WHERE user_id=?')->execute([$name,$uid]);out(['ok'=>true,'url'=>'/'.$name]);}catch(PDOException $e){out(['error'=>'Tato adresa už je obsazená.'],409);}}
if($action==='profile'){$uid=me();$s=$db->prepare('SELECT u.username,p.* FROM users u JOIN profiles p ON p.user_id=u.id WHERE u.id=?');$s->execute([$uid]);out(['ok'=>true,'profile'=>$s->fetch(PDO::FETCH_ASSOC)]);}
if($action==='save'){$uid=me();$blocks=json_encode($in['blocks']??[]);$db->prepare('UPDATE profiles SET display_name=?,bio=?,theme=?,blocks=? WHERE user_id=?')->execute([substr($in['display_name']??'',0,80),substr($in['bio']??'',0,500),$in['theme']??'violet',$blocks,$uid]);out(['ok'=>true]);}
if($action==='upload'){$uid=me();if(empty($_FILES['file'])||$_FILES['file']['error'])out(['error'=>'Soubor se nepodařilo načíst.'],422);if($_FILES['file']['size']>4*1024*1024)out(['error'=>'Maximální velikost souboru je 4 MB.'],422);$mime=mime_content_type($_FILES['file']['tmp_name']);if(!in_array($mime,['image/jpeg','image/png','image/webp']))out(['error'=>'Nahraj JPG, PNG nebo WEBP.'],422);$dir=__DIR__.'/uploads';if(!is_dir($dir))mkdir($dir);$name=bin2hex(random_bytes(12)).'.'.pathinfo($_FILES['file']['name'],PATHINFO_EXTENSION);move_uploaded_file($_FILES['file']['tmp_name'],$dir.'/'.$name);$field=$in['field']==='banner'?'banner':'avatar';$db->prepare("UPDATE profiles SET $field=? WHERE user_id=?")->execute(['/uploads/'.$name,$uid]);out(['ok'=>true,'url'=>'/uploads/'.$name]);}
out(['error'=>'Neznámá akce.'],404);
