const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
async function api(data,form){let opts=form?{method:'POST',body:form}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)};let r=await fetch('/api.php',opts);return r.json()}
function openAuth(v){$('#auth').classList.add('open');$$('.form-view').forEach(x=>x.classList.toggle('hide',x.id!==v))}$$('[data-open]').forEach(x=>x.onclick=()=>openAuth(x.dataset.open));$('.close')?.addEventListener('click',()=>$('#auth').classList.remove('open'));$$('[data-switch]').forEach(x=>x.onclick=()=>openAuth(x.dataset.switch));
$$('[data-auth]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();let r=await api({action:f.dataset.auth,...Object.fromEntries(new FormData(f))});if(r.error)return alert(r.error);if(r.next==='claim')return claim();if(r.next==='verify')return verify(r.devCode);location.href='/dashboard.php'});
function verify(code){$('.modal-box').innerHTML=`<button class="close">×</button><p class="kicker">OVĚŘENÍ E-MAILU</p><h2>Ještě jeden krok.</h2><p>Ověřovací odkaz jsme poslali do tvého e-mailu. Pro lokální demo pokračuj tlačítkem níže.</p><button class="shine" id="verify">Ověřit účet →</button>`;$('#verify').onclick=async()=>{let r=await api({action:'verify',code});if(r.ok)claim()}}
function claim(){$('.modal-box').innerHTML=`<p class="kicker">VYBER SI SVOU ADRESU</p><h2>Jak tě lidé najdou?</h2><p>Tvůj profil bude na adrese:</p><form id="claim"><label><span class="prefix">velora.cz/</span><input name="username" placeholder="itzvojtex" required pattern="[a-zA-Z0-9_-]{3,24}"></label><small>3–24 znaků: písmena, čísla, _ a -</small><button class="shine">Získat adresu →</button></form>`;$('#claim').onsubmit=async e=>{e.preventDefault();let r=await api({action:'claim',...Object.fromEntries(new FormData(e.target))});if(r.error)return alert(r.error);location.href='/dashboard.php'}}
let state={blocks:[],theme:'violet'};async function studio(){let r=await api({action:'profile'});if(!r.ok)return;state={...r.profile,blocks:JSON.parse(r.profile.blocks||'[]')};$('#user-handle').textContent='/'+state.username;$('#public-url').href='/'+state.username;$('#display-name').value=state.display_name;$('#bio').value=state.bio;render();['display-name','bio'].forEach(id=>$('#'+id).oninput=()=>{state[id.replace('-','_')]= $('#'+id).value;renderLive()});$$('.tool').forEach(b=>b.onclick=()=>{$$('.tool').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.tab').forEach(x=>x.classList.toggle('hide',x.id!==b.dataset.tab))});$$('.theme').forEach(x=>x.onclick=()=>{state.theme=x.dataset.theme;renderLive()});$('#add-block').onclick=()=>{state.blocks.push({icon:'↗',title:'Nový panel',url:''});render()};$('#save').onclick=save;$$('[data-upload]').forEach(x=>x.onchange=upload);}
function render(){let list=$('#block-list');list.innerHTML='';state.blocks.forEach((b,i)=>{let el=$('#block-template').content.firstElementChild.cloneNode(true);el.querySelector('.block-icon').value=b.icon||'';el.querySelector('.block-title').value=b.title||'';el.querySelector('.block-url').value=b.url||'';$$('input',el).forEach(input=>input.oninput=()=>{b.icon=el.querySelector('.block-icon').value;b.title=el.querySelector('.block-title').value;b.url=el.querySelector('.block-url').value;renderLive()});el.querySelector('.remove').onclick=()=>{state.blocks.splice(i,1);render()};el.ondragstart=()=>el.classList.add('dragging');el.ondragend=()=>{el.classList.remove('dragging');state.blocks=[...list.children].map(n=>state.blocks[+n.dataset.i])};el.dataset.i=i;list.append(el)});renderLive()}
function renderLive(){let c=$('#live-card');c.className='live-card t-'+state.theme;$('#live-name').textContent=state.display_name||'Profil';$('#live-handle').textContent='/'+state.username;$('#live-bio').textContent=state.bio||'';$('#live-blocks').innerHTML=state.blocks.map(x=>`<div class="live-block"><span>${x.icon||'↗'}</span><b>${x.title||'Nový panel'}</b><i>↗</i></div>`).join('')}
async function save(){let r=await api({action:'save',display_name:state.display_name,bio:state.bio,theme:state.theme,blocks:state.blocks});$('#status').textContent=r.ok?'✓ Uloženo':'Něco se nepovedlo';setTimeout(()=>$('#status').textContent='',2500)}
async function upload(e){let f=e.target.files[0];if(!f)return;let form=new FormData;form.append('action','upload');form.append('field',e.target.dataset.upload);form.append('file',f);let r=await api({},form);if(r.error)return alert(r.error);$('#'+e.target.dataset.upload+'-preview').innerHTML=`<img src="${r.url}">`;if(e.target.dataset.upload==='avatar')$('#live-avatar').innerHTML=`<img src="${r.url}">`;else $('#live-banner').style.backgroundImage=`url(${r.url})`}
if(document.body.classList.contains('studio')){let sheet=document.createElement('link');sheet.rel='stylesheet';sheet.href='/studio.css';document.head.append(sheet);studio();}if(document.body.classList.contains('public')){let sheet=document.createElement('link');sheet.rel='stylesheet';sheet.href='/profile.css';document.head.append(sheet);}
